Fixed bug in tests/runtests.py -- some versions of MySQLdb require an argument to connection.autocommit()

git-svn-id: http://code.djangoproject.com/svn/django/trunk@805 bcc190cf-cafb-0310-a4f2-bffc1f526a37
